# Standalone stack: this root ONLY manages azure_postgres.
# It has its own state (see target.tf generated by _run-terraform.sh)
module "azure_postgres_flexible" {
  source = "../../modules/azure_postgres_flexible"
  count  = var.cloud_provider == "azure" ? 1 : 0

  resource_group_name = split(".", var.cluster_domain)[0]
  location            = var.cluster_region
  cluster_name        = split(".", var.cluster_domain)[0]

  postgresql_version     = var.azure_postgres_version
  sku_name               = var.azure_postgres_sku_name
  storage_mb             = var.azure_postgres_storage_mb
  backup_retention_days  = var.azure_postgres_backup_retention_days
  high_availability_mode = var.azure_postgres_high_availability_mode
  fixed_firewall_ranges  = var.fixed_firewall_ranges

  additional_firewall_rules = var.azure_postgres_additional_firewall_rules
}
